/**
 * render-docx.js — render the collected data bundle to a Word document (.docx).
 *
 * Uses the `docx` npm package. Mirrors the structure of render-markdown.js
 * so the two outputs stay in sync.
 */

import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType,
} from 'docx';

function fmtDate(iso) {
  if (!iso) return '—';
  return new Date(iso).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
}

// ── Block helpers ───────────────────────────────────────────────────────────

function p(text, opts = {}) {
  return new Paragraph({
    spacing: { after: 120 },
    ...opts,
    children: [new TextRun({ text: text ?? '', ...opts.run })],
  });
}

function h(text, level) {
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text })],
  });
}

function bold(text) { return new TextRun({ text, bold: true }); }
function mono(text) { return new TextRun({ text, font: 'Consolas' }); }
function italic(text) { return new TextRun({ text, italics: true }); }

function bulletList(items) {
  return items.map(text =>
    new Paragraph({
      bullet: { level: 0 },
      spacing: { after: 60 },
      children: typeof text === 'string'
        ? [new TextRun({ text })]
        : text,
    })
  );
}

function codeBullet(items) {
  return items.map(text =>
    new Paragraph({
      bullet: { level: 0 },
      spacing: { after: 40 },
      children: [mono(text)],
    })
  );
}

function quote(text) {
  return new Paragraph({
    indent: { left: 720 },
    spacing: { after: 120 },
    border: { left: { color: '888888', style: BorderStyle.SINGLE, size: 6, space: 12 } },
    children: [italic(text)],
  });
}

// ── Table helpers ───────────────────────────────────────────────────────────

const HEADER_SHADING = { type: ShadingType.SOLID, color: 'EEEEEE', fill: 'EEEEEE' };

function cell(text, opts = {}) {
  return new TableCell({
    children: [
      new Paragraph({
        spacing: { after: 60 },
        children: typeof text === 'string'
          ? [new TextRun({ text, bold: opts.header ?? false })]
          : text,
      }),
    ],
    shading: opts.header ? HEADER_SHADING : undefined,
    width: opts.width ? { size: opts.width, type: WidthType.PERCENTAGE } : undefined,
  });
}

function table(headers, rows) {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: headers.map(h => cell(h, { header: true })) }),
      ...rows.map(r => new TableRow({ children: r.map(c => cell(c)) })),
    ],
  });
}

// ── Section renderers ───────────────────────────────────────────────────────

function renderTitle(data) {
  return [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: `${data.meta.projectName}`, bold: true, size: 48 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [new TextRun({ text: 'Project Documentation', size: 28 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 480 },
      children: [
        new TextRun({ text: `Current version: v${data.meta.currentVersion}\n` }),
        new TextRun({ text: `Generated: ${fmtDate(data.meta.generatedAt)}` }),
      ],
    }),
    quote('Auto-generated by vibe-reporter. Do not edit by hand — re-run /migration-report to regenerate.'),
  ];
}

function renderEnvironment(data) {
  if (!data.powerConfig) return [];
  const rows = [];
  if (data.powerConfig.appDisplayName) rows.push(['App display name', data.powerConfig.appDisplayName]);
  if (data.powerConfig.environmentId) rows.push(['Environment ID', data.powerConfig.environmentId]);
  if (data.powerConfig.region) rows.push(['Region', data.powerConfig.region]);
  if (data.powerConfig.appId) rows.push(['App ID', data.powerConfig.appId]);
  if (rows.length === 0) return [];
  return [
    h('Environment', HeadingLevel.HEADING_1),
    table(['Key', 'Value'], rows),
  ];
}

function renderOverview(data) {
  if (!data.context.glossary) return [];
  return [
    h('Overview', HeadingLevel.HEADING_1),
    p(data.context.glossary),
  ];
}

function renderArchitecture(data) {
  const out = [
    h('Architecture', HeadingLevel.HEADING_1),
    p('This project was migrated from a Power Apps Vibe source (make.powerapp.com) to a Power Code project using React + TypeScript with the @microsoft/power-apps SDK.'),
  ];
  const rows = [];
  if (data.meta.powerCodeDir) rows.push(['Power Code project folder', `${data.meta.powerCodeDir}/`]);
  rows.push(['Dataverse models', String(data.models.length)]);
  rows.push(['Connectors / data sources', String(data.connectors.length)]);
  rows.push(['npm dependencies', String(data.dependencies.length)]);
  out.push(table(['Aspect', 'Value'], rows));
  return out;
}

function renderHistoryTable(data) {
  if (data.history.length === 0) {
    return [h('Migration History', HeadingLevel.HEADING_1), italic('No version history yet.') ? p('No version history yet.', { run: { italics: true } }) : p('—')];
  }
  const rows = data.history.map(v => {
    const cf = v.changedFiles ?? { added: [], modified: [], deleted: [] };
    return [
      `v${v.version}`,
      fmtDate(v.extractedAt).slice(0, 10),
      `+${cf.added?.length ?? 0} ~${cf.modified?.length ?? 0} -${cf.deleted?.length ?? 0}`,
      String(v.fileCount ?? '—'),
      v.testResults ? `${v.testResults.passed ?? 0}P/${v.testResults.failed ?? 0}F` : '—',
      v.note || '(no note)',
    ];
  });
  return [
    h('Migration History', HeadingLevel.HEADING_1),
    table(['Version', 'Date', 'Diff', 'Files', 'Tests', 'Note'], rows),
  ];
}

function renderVersionDetails(data) {
  if (data.history.length === 0) return [];
  const out = [h('Version Details', HeadingLevel.HEADING_1)];
  for (const v of data.history) {
    out.push(h(`v${v.version} — ${fmtDate(v.extractedAt).slice(0, 10)}`, HeadingLevel.HEADING_2));
    if (v.note) out.push(quote(v.note));

    const meta = [];
    meta.push(['Files in this version', String(v.fileCount ?? '—')]);
    if (v.treeHash) meta.push(['Tree hash', v.treeHash]);
    if (v.snapshotPath) meta.push(['Snapshot', v.snapshotPath]);
    if (v.gitTag) meta.push(['Git tag', v.gitTag]);
    if (v.testResults) {
      meta.push([
        `Tests (run at ${fmtDate(v.testResults.runAt)})`,
        `${v.testResults.passed ?? 0} passed, ${v.testResults.failed ?? 0} failed, ${v.testResults.skipped ?? 0} skipped (${((v.testResults.durationMs ?? 0) / 1000).toFixed(1)}s)`,
      ]);
    }
    out.push(table(['Key', 'Value'], meta));

    const cf = v.changedFiles ?? { added: [], modified: [], deleted: [] };
    if (cf.added?.length) {
      out.push(p('Added files:', { run: { bold: true } }));
      out.push(...codeBullet(cf.added));
    }
    if (cf.modified?.length) {
      out.push(p('Modified files:', { run: { bold: true } }));
      out.push(...codeBullet(cf.modified));
    }
    if (cf.deleted?.length) {
      out.push(p('Deleted files:', { run: { bold: true } }));
      out.push(...codeBullet(cf.deleted));
    }
  }
  return out;
}

function renderFieldMappings(data) {
  if (!data.context.fieldMappings) return [];
  return [
    h('Field Mappings', HeadingLevel.HEADING_1),
    p('Friendly Vibe field names ↔ raw Dataverse field names. The adapter layer (src/generated/services/) translates between them.'),
    p(data.context.fieldMappings),
  ];
}

function renderDataSources(data) {
  if (data.models.length === 0 && data.connectors.length === 0) return [];
  const out = [h('Data Sources', HeadingLevel.HEADING_1)];
  if (data.models.length > 0) {
    out.push(p('Dataverse models:', { run: { bold: true } }));
    out.push(...codeBullet(data.models));
  }
  if (data.connectors.length > 0) {
    out.push(p('Connectors:', { run: { bold: true } }));
    out.push(...codeBullet(data.connectors));
    out.push(quote('All connector calls go through executeAsync({ connectorOperation }) from @microsoft/power-apps/data — direct fetch() is blocked by the Power Apps player CSP.'));
  }
  return out;
}

function renderOwnership(data) {
  if (!data.ownership) return [];
  const out = [
    h('File Ownership', HeadingLevel.HEADING_1),
    p('From vibe-migration.json. Determines what incremental updates may auto-apply vs. require human review.'),
  ];
  if (data.ownership.vibeOwned.length > 0) {
    out.push(p(`Vibe-owned (${data.ownership.vibeOwned.length} files — safe to auto-update from new extractions):`, { run: { bold: true } }));
    out.push(...codeBullet(data.ownership.vibeOwned));
  }
  if (data.ownership.migrationOwned.length > 0) {
    out.push(p(`Migration-owned (${data.ownership.migrationOwned.length} files — never auto-overwritten):`, { run: { bold: true } }));
    out.push(...codeBullet(data.ownership.migrationOwned));
  }
  if (data.ownership.requiresReview.length > 0) {
    out.push(p(`Requires review (${data.ownership.requiresReview.length} files — diff shown, manual confirm):`, { run: { bold: true } }));
    out.push(...codeBullet(data.ownership.requiresReview));
  }
  return out;
}

function renderAdrs(data) {
  if (data.adrs.length === 0) return [];
  const out = [h('Architecture Decisions (ADRs)', HeadingLevel.HEADING_1)];
  for (const adr of data.adrs) {
    out.push(h(adr.title, HeadingLevel.HEADING_2));
    out.push(p(`Source: docs/adr/${adr.filename}`, { run: { italics: true } }));
    const body = adr.body.replace(/^#\s+.+\n+/, '');
    // Split on blank lines to make paragraphs
    for (const para of body.split(/\n\s*\n/)) {
      if (para.trim()) out.push(p(para.trim()));
    }
  }
  return out;
}

function renderDependencies(data) {
  if (data.dependencies.length === 0) return [];
  const out = [h('Dependencies', HeadingLevel.HEADING_1)];
  out.push(p('Runtime:', { run: { bold: true } }));
  out.push(...codeBullet(data.dependencies));
  if (data.devDependencies.length > 0) {
    out.push(p('Development:', { run: { bold: true } }));
    out.push(...codeBullet(data.devDependencies));
  }
  return out;
}

function renderFooter(data) {
  return [
    new Paragraph({
      spacing: { before: 480 },
      alignment: AlignmentType.CENTER,
      children: [italic(`Generated by vibe-reporter at ${fmtDate(data.meta.generatedAt)}.`)],
    }),
  ];
}

// ── Public entry ────────────────────────────────────────────────────────────

/**
 * @param {object} data  Output of collect()
 * @returns {Promise<Buffer>}  The .docx file as a Buffer
 */
export async function renderDocx(data) {
  const children = [
    ...renderTitle(data),
    ...renderEnvironment(data),
    ...renderOverview(data),
    ...renderArchitecture(data),
    ...renderHistoryTable(data),
    ...renderVersionDetails(data),
    ...renderFieldMappings(data),
    ...renderDataSources(data),
    ...renderOwnership(data),
    ...renderAdrs(data),
    ...renderDependencies(data),
    ...renderFooter(data),
  ];

  const doc = new Document({
    creator: 'vibe-reporter',
    title: `${data.meta.projectName} — Project Documentation`,
    description: `Auto-generated project documentation @ v${data.meta.currentVersion}`,
    styles: {
      default: {
        document: { run: { font: 'Calibri', size: 22 } },
      },
    },
    sections: [{ properties: {}, children }],
  });

  return Packer.toBuffer(doc);
}
