/**
 * render-docx.js — render the system model to docs/SYSTEM.docx
 *
 * Mirrors render-md.js structure so the two outputs stay aligned. The
 * Solution Graph section embeds the same three views (ASCII as a code
 * paragraph, Mermaid source as a code paragraph, JSON spec as a code
 * paragraph). No rasterised PNG — keeps the doc machine-parseable and
 * avoids a Chromium dep just to render diagrams.
 */

import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType, PageBreak,
} from 'docx';

function fmtDate(iso) {
  if (!iso) return '—';
  return new Date(iso).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
}

// ── Block helpers ───────────────────────────────────────────────────────────

function p(text, opts = {}) {
  return new Paragraph({
    spacing: { after: 120 },
    ...opts,
    children: [new TextRun({ text: text ?? '', ...opts.run })],
  });
}

function h(text, level) {
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text })],
  });
}

function bold(text) { return new TextRun({ text, bold: true }); }
function mono(text) { return new TextRun({ text, font: 'Consolas', size: 18 }); }
function italic(text) { return new TextRun({ text, italics: true }); }

function bulletList(items) {
  return items.map(text =>
    new Paragraph({
      bullet: { level: 0 },
      spacing: { after: 60 },
      children: [new TextRun({ text })],
    })
  );
}

function codeBlock(text) {
  // Render multi-line code as a single paragraph per line with monospaced font.
  const lines = text.split('\n');
  return lines.map(line =>
    new Paragraph({
      spacing: { after: 0 },
      shading: { type: ShadingType.SOLID, color: 'F5F5F5', fill: 'F5F5F5' },
      children: [mono(line || ' ')],
    })
  );
}

function quote(text) {
  return new Paragraph({
    indent: { left: 720 },
    spacing: { after: 120 },
    border: { left: { color: '888888', style: BorderStyle.SINGLE, size: 6, space: 12 } },
    children: [italic(text)],
  });
}

// ── Table helpers ───────────────────────────────────────────────────────────

const HEADER_SHADING = { type: ShadingType.SOLID, color: 'EEEEEE', fill: 'EEEEEE' };

function cell(content, opts = {}) {
  const children = typeof content === 'string'
    ? [new Paragraph({ spacing: { after: 40 }, children: [new TextRun({ text: content, bold: opts.header })] })]
    : Array.isArray(content) ? content : [content];
  return new TableCell({
    children,
    shading: opts.header ? HEADER_SHADING : undefined,
    width: opts.width ? { size: opts.width, type: WidthType.PERCENTAGE } : undefined,
  });
}

function table(headers, rows) {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: headers.map(h => cell(h, { header: true })) }),
      ...rows.map(r => new TableRow({ children: r.map(c => cell(c)) })),
    ],
  });
}

// ── Section renderers ───────────────────────────────────────────────────────

function renderCover(model) {
  return [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { before: 1440, after: 240 },
      children: [new TextRun({ text: model.name, bold: true, size: 56 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 480 },
      children: [new TextRun({ text: 'System Documentation', size: 32 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [new TextRun({ text: `Version ${model.version}`, size: 24 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [new TextRun({ text: `Generated ${fmtDate(new Date().toISOString())}`, size: 20 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 720 },
      children: [new TextRun({ text: `Repository: ${model.repo}`, size: 18 })],
    }),
    quote(`Auto-generated by vibe-toolkit-doc. Do not edit by hand — edit vibe-toolkit-doc/lib/system-model.js and re-run node vibe-toolkit-doc/index.js.`),
    new Paragraph({ children: [new PageBreak()] }),
  ];
}

function renderBusinessPurpose(model) {
  return [
    h('Business Purpose', HeadingLevel.HEADING_1),
    p(model.businessPurpose),
  ];
}

function renderExecutiveSummary(model) {
  return [
    h('Executive Summary', HeadingLevel.HEADING_1),
    p(model.executiveSummary),
  ];
}

function renderSystemOverview(model) {
  const counts = {};
  for (const n of model.nodes) counts[n.type] = (counts[n.type] ?? 0) + 1;
  const rows = Object.entries(counts).map(([t, c]) => [t, String(c)]);
  return [
    h('System Overview', HeadingLevel.HEADING_1),
    p('The toolkit is composed of:'),
    table(['Component type', 'Count'], rows),
    p(''),
    p(`Plus ${model.edges.length} explicit relationships between them, ${model.flows.length} named data flows, and ${model.impactAnalysis.length} impact-analysis entries.`),
  ];
}

function renderAsciiGraph() {
  return [
    '                           ┌─────────────┐',
    '                           │  developer  │',
    '                           └──────┬──────┘',
    '            ┌─────────────────────┼──────────────────────┐',
    '            ▼                     ▼                      ▼',
    '   ┌────────────────┐   ┌──────────────────┐   ┌──────────────────┐',
    '   │ vibe-extractor │   │   claude-code    │   │  vibe-verifier   │',
    '   │  (Playwright)  │   │   (skills/*)     │   │  (Playwright)    │',
    '   └────────┬───────┘   └────────┬─────────┘   └────────┬─────────┘',
    '            │                    │                       │',
    '            │ writes             │ reads + writes        │ reads/writes',
    '            ▼                    ▼                       ▼',
    '   ┌────────────────────────────────────────────────────────────────┐',
    '   │   vibe-source/  vibe-baseline/  vibe-history.json              │',
    '   │   vibe-pending-update.json  vibe-migration.json                │',
    '   │   vibe-baselines-snapshots/v*/                                 │',
    '   └─────────────────────────────┬──────────────────────────────────┘',
    '                                 │                ┌──────────────────┐',
    '                                 ▼                │  vibe-reporter   │',
    '                       ┌──────────────────┐       │  (docx)          │',
    '                       │ [ProjectName]/   │◄──────┤                  │',
    '                       │ (Power Code app) │       └────────┬─────────┘',
    '                       └────────┬─────────┘                │',
    '                                │ npx power-apps push      ▼',
    '                                ▼                ┌──────────────────┐',
    '                       ┌──────────────────┐      │ docs/PROJECT.md  │',
    '                       │ Power Apps player│      │ docs/PROJECT.docx│',
    '                       │ (deployed app)   │      └──────────────────┘',
    '                       └────────┬─────────┘',
    '                                │',
    '                                │ tests run against',
    '                                ▼',
    '                       ┌──────────────────┐      ┌──────────────────┐',
    '                       │   tests/specs/   │─────▶│  github (issues) │',
    '                       │   tests/results/ │      │   via gh CLI     │',
    '                       └──────────────────┘      └──────────────────┘',
  ].join('\n');
}

function renderMermaidSource(model) {
  const lines = ['graph TD'];
  for (const n of model.nodes) {
    const label = n.id.replace(/[:/]/g, '_');
    const text = `${n.id} (${n.type})`;
    lines.push(`    ${label}["${text}"]`);
  }
  for (const e of model.edges) {
    const fromLabel = e.from.replace(/[:/]/g, '_');
    const toLabel = e.to.replace(/[:/]/g, '_');
    lines.push(`    ${fromLabel} -->|${e.type}| ${toLabel}`);
  }
  return lines.join('\n');
}

function renderJsonGraph(model) {
  const nodes = model.nodes.map(n => ({
    id: n.id,
    type: n.type,
    location: n.location ?? null,
    entrypoint: n.entrypoint ?? null,
    invokedAs: n.invokedAs ?? null,
    ownership: n.ownership ?? null,
  }));
  const edges = model.edges.map(e => ({ from: e.from, to: e.to, type: e.type }));
  return JSON.stringify({ nodes, edges }, null, 2);
}

function renderSolutionGraph(model) {
  return [
    h('Solution Graph', HeadingLevel.HEADING_1),
    p('Three representations of the same graph. Use whichever fits your viewer:'),
    h('View 1 — ASCII diagram (for any text viewer)', HeadingLevel.HEADING_2),
    ...codeBlock(renderAsciiGraph()),
    h('View 2 — Mermaid (renders in GitHub, VS Code, many Markdown viewers)', HeadingLevel.HEADING_2),
    p('Paste this into mermaid.live or any Mermaid-aware viewer:'),
    ...codeBlock(renderMermaidSource(model)),
    h('View 3 — JSON graph spec (for AI agents)', HeadingLevel.HEADING_2),
    p('Parse this directly. Each node has id, type, location, entrypoint, invokedAs, ownership. Each edge is {from, to, type}.'),
    ...codeBlock(renderJsonGraph(model)),
    new Paragraph({ children: [new PageBreak()] }),
  ];
}

function renderComponentCatalog(model) {
  const out = [h('Component Catalog', HeadingLevel.HEADING_1)];
  const grouped = {};
  for (const n of model.nodes) (grouped[n.type] ??= []).push(n);
  for (const [type, nodes] of Object.entries(grouped)) {
    out.push(h(`Type: ${type} (${nodes.length})`, HeadingLevel.HEADING_2));
    for (const n of nodes) {
      out.push(h(n.id, HeadingLevel.HEADING_3));
      out.push(p(n.description));
      const metaRows = [];
      if (n.location) metaRows.push(['Location', n.location]);
      if (n.entrypoint) metaRows.push(['Entrypoint', n.entrypoint]);
      if (n.invokedAs) metaRows.push(['Invoked as', n.invokedAs]);
      if (n.flags) metaRows.push(['Flags', n.flags.join(', ')]);
      if (n.dependencies) metaRows.push(['Dependencies', n.dependencies.join(', ')]);
      if (n.schema) metaRows.push(['Schema', n.schema]);
      if (n.ownership) metaRows.push(['Ownership', n.ownership]);
      if (metaRows.length > 0) {
        out.push(table(['Field', 'Value'], metaRows));
      }
    }
  }
  return out;
}

function renderDataFlows(model) {
  const out = [h('Data Flows', HeadingLevel.HEADING_1)];
  for (const flow of model.flows) {
    out.push(h(`Flow: ${flow.name}`, HeadingLevel.HEADING_2));
    out.push(p('Trigger:', { run: { bold: true } }));
    out.push(p(flow.trigger));
    out.push(p('Steps:', { run: { bold: true } }));
    flow.steps.forEach((s, i) =>
      out.push(
        new Paragraph({
          numbering: { reference: 'flow-steps', level: 0 },
          spacing: { after: 60 },
          children: [new TextRun({ text: s })],
        })
      )
    );
  }
  return out;
}

function renderRelationshipMatrix(model) {
  const by = { reads: {}, writes: {}, appends: {}, invokes: {}, triggers: {}, 'depends-on': {} };
  for (const e of model.edges) {
    if (!by[e.type]) continue;
    (by[e.type][e.to] ??= []).push(e.from);
  }
  const out = [h('Relationship Matrix', HeadingLevel.HEADING_1)];
  out.push(p('Reverse-lookup: for each target, who acts on it. AI agents can use this to answer "what breaks if I change X?" without re-traversing the edge list.'));
  for (const [type, map] of Object.entries(by)) {
    if (Object.keys(map).length === 0) continue;
    out.push(h(type, HeadingLevel.HEADING_2));
    const rows = Object.entries(map).sort().map(([target, actors]) => [target, actors.join(', ')]);
    out.push(table(['Target', 'Actors'], rows));
  }
  return out;
}

function renderImpactAnalysis(model) {
  const out = [
    h('Impact Analysis', HeadingLevel.HEADING_1),
    p('What changes when you modify or remove each significant component.'),
  ];
  for (const item of model.impactAnalysis) {
    out.push(h(item.component, HeadingLevel.HEADING_2));
    if (item.ifModified) {
      out.push(p('If modified:', { run: { bold: true } }));
      out.push(p(item.ifModified));
    }
    if (item.breaksIfRemoved) {
      out.push(p('Breaks if removed:', { run: { bold: true } }));
      out.push(...bulletList(item.breaksIfRemoved));
    }
    if (item.criticalInvariants) {
      out.push(p('Critical invariants:', { run: { bold: true } }));
      out.push(...bulletList(item.criticalInvariants));
    }
  }
  return out;
}

function renderFooter() {
  return [
    new Paragraph({
      spacing: { before: 480 },
      alignment: AlignmentType.CENTER,
      children: [italic(`Generated by vibe-toolkit-doc at ${fmtDate(new Date().toISOString())}.`)],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [italic('Edit the source model: vibe-toolkit-doc/lib/system-model.js — never edit this file directly.')],
    }),
  ];
}

// ── Public entry ────────────────────────────────────────────────────────────

export async function renderDocx(model) {
  const children = [
    ...renderCover(model),
    ...renderBusinessPurpose(model),
    ...renderExecutiveSummary(model),
    ...renderSystemOverview(model),
    ...renderSolutionGraph(model),
    ...renderComponentCatalog(model),
    ...renderDataFlows(model),
    ...renderRelationshipMatrix(model),
    ...renderImpactAnalysis(model),
    ...renderFooter(),
  ];

  const doc = new Document({
    creator: 'vibe-toolkit-doc',
    title: `${model.name} — System Documentation`,
    description: `Auto-generated system documentation at v${model.version}`,
    numbering: {
      config: [
        {
          reference: 'flow-steps',
          levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.START }],
        },
      ],
    },
    styles: {
      default: { document: { run: { font: 'Calibri', size: 22 } } },
    },
    sections: [{ properties: {}, children }],
  });

  return Packer.toBuffer(doc);
}
